service:
  type: LoadBalancer
  loadBalancerIP: 158.36.191.228

dashboard:
  enabled: true

ports:
  web:
    redirectTo: websecure

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

