apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  volumeMode: Filesystem
  accessModes:
{{- range .Values.accessModes }}
    - {{ . }}
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.persistentVolume.nfs.path }}
    server: {{ .Values.persistentVolume.nfs.server }}
