apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pgbackup-pv
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pgbackup-pvc
  namespace: {{ .Values.nfs.namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.request }}

