apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubegres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reactive-tech/kubegres.git
    targetRevision: v1.19
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kubegres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

