apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: v35.4.0
    helm:
      values: |
        persistence:
          enabled: true

        securityContext:
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsUser: 0
          runAsNonRoot: false

        deployment:
          initContainers:
          - name: volume-permissions
            image: busybox:1.35.0
            command: ["sh", "-c", "chmod -Rv 600 /data/ || true"]
            volumeMounts:
              - name: data
                mountPath: /data

        certificatesResolvers:
          letsencrypt:
            acme:
              email: toresbe@protonmail.com
              storage: /data/acme.json
              httpChallenge:
                entryPoint: web

        service:
          type: LoadBalancer

        dashboard:
          enabled: true

        podSecurityContext:
          fsGroup: null
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
